### ISSUE TITLE
Issues found during DocC migration review

### ISSUE THREAD

**Issue by dfeinzimer** [Esri/arcgis-maps-sdk-swift-toolkit#406]
This is a tracking issue for suggestions made during review of #392.

## All Components, Examples & Tutorials

- [x] Sort all imports (precedent [here](https://devtopia.esri.com/runtime/swift/pull/4411#discussion_r1029570) and [here](https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/pull/392#discussion_r1295072966)) #689 
- [x] Preambles with empty lines (see [here](https://github.com/Esri/Dejavu/pull/14#discussion_r1308889994)) #537

## Multiple Examples & Tutorials

- [x] https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/pull/392#discussion_r1295059513 #681 

## `Authenticator`

- [x] https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/pull/392#discussion_r1295003207
- [x] https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/pull/392#discussion_r1295011502
- [x] https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/pull/392#discussion_r1295015735
- [x] https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/pull/392#discussion_r1295041825
- [x] https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/commit/1e13232c5420a8e41928453cba586f55d93bb3f7#r124597719

## `BasemapGallery`

- [x] https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/pull/392#discussion_r1294872695
- [x] https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/pull/392#discussion_r1295029122 #687
- [x] https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/pull/392#discussion_r1295038501

## `Bookmarks`

- [x] https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/pull/392#discussion_r1295043896 #549 
- [x] https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/pull/392#discussion_r1295084387 #549 

## `FloatingPanel`

  - [x] https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/pull/392#discussion_r1295054040 #682
  - [x] https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/pull/392#discussion_r1294989490 #682

## `FloorFilter`

- [x] https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/pull/392#discussion_r1294948228 #478

## `OverviewMap`

- Example & Tutorial
  - [x] https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/pull/392#discussion_r1295062026 #686

## `PopupView`

- Example & Tutorial
  - [x] #408 [Suggestion](https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/pull/392#discussion_r1295085884)
- Tutorial Only
  - [x] #408 Synchronize the tutorial with the example. Changes were made to the example at the very end of the release.

## `Scalebar`

- [x] https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/pull/392#discussion_r1294959244 #685

## `UtilityNetworkTrace`

- Example & Tutorial
  - [x] https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/pull/392#discussion_r1295072406 #684

**Comment by dfeinzimer** [comment]
Closing - all of the feedback mentioned in this issue has been previously resolved, moved into more focused issues with smaller scope or been addressed via a PR linked above.
